from enum import Enum


class OcpiTokenTypeEnum(str, Enum):
    '''
    OCPI 12.4.4. TokenType enum
    '''
    AD_HOC_USER = 'AD_HOC_USER' # One time use Token ID generated by a server (or App.)
    APP_USER = 'APP_USER' # Token ID generated by a server (or App.) to identify a user of an App.
    OTHER = 'OTHER' # Other type of token
    RFID = 'RFID' # RFID